from app.models import db, Patient


def seed_patients():
    patients = [
        Patient(first_name='Eddie', last_name='Marshall', address='Mirror Park Blvd', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Mary', last_name='Mushkin',
                address='North Rockford Drive', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Ramee', last_name='El-Rahman',
                address='Vespucci Blvd', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Randy', last_name='Bullet',
                address='Vespucci Blvd', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Michael', last_name='Simone',
                address='Magellan', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Nicholas', last_name='Simone',
                address='Magellan', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Jim', last_name='Underwood',
                address='San Andreas Avenue', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Mickey', last_name='S',
                address='Ace Jones Drive', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
        Patient(first_name='Lang', last_name='Buddha',
                address='Ace Jones Drive', notes='<p><strong>Physical Health</strong></p><p><br></p><p>Lorem ipsum dolor sit amet, cu sonet diceret interesset duo, eam soleat forensibus sadipscing te. Est in sententiae appellantur. Ut populo contentiones cum, eam ex ancillae sensibus. Eos at euripidis moderatius.</p><p><br></p><p><strong>Drug Use</strong></p><p><br></p><p>Cum blandit pertinax scribentur ea, duo ad case inermis. Ex quo lucilius antiopam, cum ad quis quidam albucius. Cum et tale mnesarchum sententiae. Mel alii vide iusto ad, facilisi consulatu signiferumque sed at. Vim an impetus eleifend repudiare, eu his antiopam pericula mediocrem.</p><p><br></p><p><strong>Family History</strong></p><p><br></p><p>No primis deserunt concludaturque mea, ex malis latine liberavisse est, sed tation nusquam intellegam id. Timeam patrioque mel et. Ei cum elitr nemore ancillae, sit id liber quando salutandi. Mazim animal te pro. At elit dictas evertitur vel. Case vituperata repudiandae pro ex, molestie torquatos adolescens pri an.</p>'),
    ]

    db.session.add_all(patients)
    db.session.commit()


def undo_patients():
    db.session.execute('TRUNCATE patients RESTART IDENTITY CASCADE;')
    db.session.commit()
