"""empty message

Revision ID: ab3415164487
Revises: fddb5efca740
Create Date: 2022-09-24 10:13:44.259662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3415164487'
down_revision = 'fddb5efca740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('notes', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'notes')
    # ### end Alembic commands ###
