"""empty message

Revision ID: 931a68283ff7
Revises: c241cc8bfb18
Create Date: 2022-09-28 07:56:00.791119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931a68283ff7'
down_revision = 'c241cc8bfb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departmentreports',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], )
    )
    op.create_table('patientreports',
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], )
    )
    op.create_table('staffreports',
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffreports')
    op.drop_table('patientreports')
    op.drop_table('departmentreports')
    op.drop_table('reports')
    # ### end Alembic commands ###
