"""empty message

Revision ID: fa278fb12505
Revises: a5f1279d50d6
Create Date: 2022-09-26 14:12:55.340242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa278fb12505'
down_revision = 'a5f1279d50d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('building', sa.String(length=100), nullable=False))
    op.add_column('departments', sa.Column('floor', sa.String(length=100), nullable=False))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('departments', 'floor')
    op.drop_column('departments', 'building')
    # ### end Alembic commands ###
