"""empty message

Revision ID: 5f59858cbc12
Revises: ab3415164487
Create Date: 2022-09-24 18:27:15.515349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f59858cbc12'
down_revision = 'ab3415164487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=5000), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=500), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageURL', sa.String(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('staffs_first_name_key', 'staffs', type_='unique')
    op.drop_constraint('staffs_last_name_key', 'staffs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('staffs_last_name_key', 'staffs', ['last_name'])
    op.create_unique_constraint('staffs_first_name_key', 'staffs', ['first_name'])
    op.drop_table('images')
    op.drop_table('patients')
    # ### end Alembic commands ###
