"""empty message

Revision ID: b8640106cdcf
Revises: 8a7201d69ae7
Create Date: 2022-11-03 15:26:57.718438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8640106cdcf'
down_revision = '8a7201d69ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('conditions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'updated_at')
    op.drop_column('conditions', 'created_at')
    # ### end Alembic commands ###
