"""empty message

Revision ID: c241cc8bfb18
Revises: d9736adc8335
Create Date: 2022-09-27 11:04:08.621041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c241cc8bfb18'
down_revision = 'd9736adc8335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'emergency_contact_name')
    op.drop_column('patients', 'emergency_contact_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('emergency_contact_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
