"""empty message

Revision ID: a5f1279d50d6
Revises: dbd4586a7f68
Create Date: 2022-09-26 11:45:23.071152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f1279d50d6'
down_revision = 'dbd4586a7f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departments_location_key', 'departments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('departments_location_key', 'departments', ['location'])
    # ### end Alembic commands ###
